services:
  guidely-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: haoyu99/noumena_guidely:main
    container_name: guidely-webui
    volumes:
      - /mnt/dev-data/guidely-webui:/app/backend/data
    ports:
      - "3200:8080"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      - DATABASE_URL=postgres://postgres:noumena_guidely@10.0.16.5:3600/guidely
      - DATABASE_POOL_SIZE=10
      - DATABASE_POOL_MAX_OVERFLOW=20
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped